# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bi_yr0aFGY6g99tE__uErkm3NMtBG0Q-
"""

import numpy as np

class NearestNeighbor:

  def __init__(self):
    pass

  def train(self,X,y):
    self.Xtr = X
    self.ytr = y

  def predict(self,X):
    num_test = X.shape[0]
    Ypred = np.zeros(num_test, dtype = self.ytr.dtype)

    for i in range(num_test):
      distances = np.sum(np.abs(self.Xtr - X[i,:]), axis = 1)
      min_index = np.argmin(distances)
      Ypred[i] = self.ytr[min_index]

    return Ypred